---
Schedule:
    Ping: 5 Minutes # Minutes or Hours
    Speedtest: OFF # Minutes, Hours or OFF (official Ookla Speedtest CLI required)
    Archiving: 14 Days # Minutes, Hours or Days

Addresses:
    Gateway:
        IPv4: 192.168.1.1
    Cloudflare DNS:
        IPv6: 2606:4700:4700::1111
        IPv4: 1.1.1.1
    Youtube:
        Domain: youtube.com
        Protocol: Both # IPv4, IPv6 or Both
